/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as InterviewQuestionsRouteImport } from './routes/interview/questions'
import { Route as InterviewSetupRouteImport } from './routes/interview/setup'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as HomeRouteImport } from './routes/home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewQuestionsRoute = InterviewQuestionsRouteImport.update({
  id: '/interview/questions',
  path: '/interview/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSetupRoute = InterviewSetupRouteImport.update({
  id: '/interview/setup',
  path: '/interview/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/termos': typeof TermosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/interview/questions': typeof InterviewQuestionsRoute
  '/interview/setup': typeof InterviewSetupRoute
  '/audit': typeof AuditRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/termos': typeof TermosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/interview/questions': typeof InterviewQuestionsRoute
  '/interview/setup': typeof InterviewSetupRoute
  '/audit': typeof AuditRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/termos': typeof TermosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/interview/questions': typeof InterviewQuestionsRoute
  '/interview/setup': typeof InterviewSetupRoute
  '/audit': typeof AuditRoute
  '/home': typeof HomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/register' | '/termos' | '/privacidade' | '/interview/questions' | '/interview/setup' | '/audit' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/register' | '/termos' | '/privacidade' | '/interview/questions' | '/interview/setup' | '/audit' | '/home'
  id: '__root__' | '/' | '/register' | '/termos' | '/privacidade' | '/interview/questions' | '/interview/setup' | '/audit' | '/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  TermosRoute: typeof TermosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  InterviewQuestionsRoute: typeof InterviewQuestionsRoute
  InterviewSetupRoute: typeof InterviewSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/questions': {
      id: '/interview/questions'
      path: '/interview/questions'
      fullPath: '/interview/questions'
      preLoaderRoute: typeof InterviewQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/setup': {
      id: '/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof InterviewSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  TermosRoute: TermosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  InterviewQuestionsRoute: InterviewQuestionsRoute,
  InterviewSetupRoute: InterviewSetupRoute,
  AuditRoute: AuditRoute,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}